//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_CAMERA_INFO
    {
        public string ID { get; set; }
        public string ASSET_ID { get; set; }
        public string CAMERA_NO { get; set; }
        public string POSITION_CODE { get; set; }
        public Nullable<decimal> POSITION_ID { get; set; }
        public string CAMERA_NAME { get; set; }
        public Nullable<decimal> ORG_ID { get; set; }
        public string ADDRESS { get; set; }
        public string CAMERA_IP { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string SN { get; set; }
        public string CAMERA_MODEL { get; set; }
        public string MANUFACTURER { get; set; }
        public string SUPPLIER { get; set; }
        public string CAMERA_STATE { get; set; }
        public string ADD_ID { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
        public string USER_NAME { get; set; }
        public string PASS_WORD { get; set; }
        public Nullable<short> CASE_INSTALL_TYPE { get; set; }
        public string AREA_CODE { get; set; }
        public string MONITOR_TYPE { get; set; }
        public string POINT_NAME { get; set; }
        public string CAMERA_IP6 { get; set; }
        public string SUBNET_MASK { get; set; }
        public string GATEWAY { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string ONU_SN { get; set; }
        public string CAMERA_TYPE { get; set; }
        public string CAMERA_FUN_TYPE { get; set; }
        public Nullable<short> FILL_LIGTH_ATTR { get; set; }
        public Nullable<short> CAMERA_ENCODE_TYPE { get; set; }
        public Nullable<short> POWER_TAKE_TYPE { get; set; }
        public string POWER_TAKE_LENGTH { get; set; }
        public Nullable<short> SOUND_ALARM { get; set; }
        public string RESOLUTION { get; set; }
        public string SOFT_VERSION { get; set; }
        public string LENS_PARAM { get; set; }
        public Nullable<short> IS_HAVE_CONSOLE { get; set; }
        public string INSTALL_WAY { get; set; }
        public string LINEAR_WAY { get; set; }
        public string RESOURCE_PLACE { get; set; }
        public string IMPORT_WATCH { get; set; }
        public string WATCH_UNITS { get; set; }
        public string POSITION_TYPE { get; set; }
        public string COMMUNITY { get; set; }
        public string STREET { get; set; }
        public string WATCH_SPEC_LOCATION { get; set; }
        public string ROAD_DIRECTION { get; set; }
        public string FOUL_LINE { get; set; }
        public string FEN_JU { get; set; }
        public string POLICE_STATION { get; set; }
        public string CAMERA_DIRECTION { get; set; }
        public string INSTALL_HEIGHT { get; set; }
        public string CROSS_ARM1 { get; set; }
        public string CROSS_ARM2 { get; set; }
        public Nullable<short> INDOOR_OR_NOT { get; set; }
        public string SPECIAL_PHOTO_PATH { get; set; }
        public string LOCATION_PHOTO_PATH { get; set; }
        public string REAL_PHOTO_PATH { get; set; }
        public Nullable<short> NETWORK_PROPERTIES { get; set; }
        public string POLICE_AREA_CODE { get; set; }
        public string INSTALL_PERSION { get; set; }
        public Nullable<System.DateTime> INSTALL_TIME { get; set; }
        public Nullable<short> BUILD_PERIOD { get; set; }
        public string PROJECT_NAME { get; set; }
        public string MANAGER_UNIT { get; set; }
        public string MANAGER_UNIT_TEL { get; set; }
        public string MAINTAIN_UNIT { get; set; }
        public string MAINTAIN_UNIT_TEL { get; set; }
        public Nullable<short> RECODE_SAVE_TYPE { get; set; }
        public Nullable<short> DEVICE_STATE { get; set; }
        public string INDUSTRY_OWN { get; set; }
        public Nullable<short> IS_REGISTER_IMOS { get; set; }
        public Nullable<short> IS_WIFI { get; set; }
        public Nullable<short> IS_FLASH { get; set; }
        public string CAMERA_NO_STR { get; set; }
        public string CAMERA_VCN_CODE { get; set; }
        public string FIELD_NO { get; set; }
        public string KEY_UNIT { get; set; }
        public string UNIT_TYPE { get; set; }
        public Nullable<decimal> SHOW_LEVEL { get; set; }
        public string PROTOCOL_TYPE { get; set; }
        public string CAMERA_PORT { get; set; }
        public string INTERFACE_TYPE { get; set; }
        public string CHANNEL { get; set; }
        public string USER_OBJECT { get; set; }
        public string IMG_PATH { get; set; }
        public string CAMERA_DESC { get; set; }
        public Nullable<short> IS_REGISTER_VCN { get; set; }
        public short IS_DEL { get; set; }
        public Nullable<int> ORDER_VALUE { get; set; }
        public Nullable<short> POLLING_RESULT { get; set; }
        public Nullable<System.DateTime> POLLING_TIME { get; set; }
        public Nullable<decimal> SERVER_ID { get; set; }
        public string SHORT_MSG { get; set; }
        public string CAMERA_BELONGS_ID { get; set; }
        public string RELATED_CUSTOMS { get; set; }
        public Nullable<short> ADDED_TO_SDE { get; set; }
        public string CAMERA_BAK { get; set; }
        public string CAMERA_BELONGS_PK { get; set; }
        public string MEMBERBAR_CODE { get; set; }
        public Nullable<decimal> IS_BRANCH { get; set; }
        public Nullable<short> IS_WATCHPOS { get; set; }
    }
}
