//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_USER_INFO
    {
        public decimal ID { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<short> IS_MUST_MODIFY_PSD { get; set; }
        public string REAL_NAME { get; set; }
        public string PINYIN { get; set; }
        public Nullable<decimal> SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<decimal> ORG_ID { get; set; }
        public string JOB_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> USER_TYPE { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_TIME { get; set; }
        public string LAST_LOGIN_IP { get; set; }
        public Nullable<decimal> LOGIN_COUNT { get; set; }
        public string QQ_NO { get; set; }
        public string MSN_NO { get; set; }
        public string HOME_ADDRESS { get; set; }
        public string USER_AVATAR { get; set; }
        public string VCN_USER_ID { get; set; }
        public string VCN_STR { get; set; }
        public Nullable<short> PTZ_LEVEL { get; set; }
        public Nullable<short> IS_USE_VALIDITY { get; set; }
        public Nullable<System.DateTime> VALIDITY_BEGIN_DATE { get; set; }
        public Nullable<System.DateTime> VALIDITY_END_DATE { get; set; }
        public string SUB_SYS_PRIVILEGE { get; set; }
        public short IS_DEL { get; set; }
        public short ORDER_VALUE { get; set; }
        public Nullable<decimal> ADD_ID { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public Nullable<decimal> MODIFY_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
        public Nullable<short> CHANGE_FLAG { get; set; }
    }
}
