//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIPF_CASE
    {
        public string ID { get; set; }
        public string WARNING_CODE { get; set; }
        public string CASE_CODE { get; set; }
        public string CASE_ORGID { get; set; }
        public string CASE_HANDLERECORD { get; set; }
        public string CASE_JURISEDITION { get; set; }
        public string CASE_ADMIN { get; set; }
        public string CASE_POLICES { get; set; }
        public string CASE_LONGITUDE { get; set; }
        public string CASE_LITATUDE { get; set; }
        public string CASE_FROM { get; set; }
        public string CASE_CREATOR { get; set; }
        public string CASE_ADDRESS { get; set; }
        public string CASE_NAME { get; set; }
        public Nullable<System.DateTime> CASE_STARTTIME { get; set; }
        public Nullable<System.DateTime> CASE_ENDTIME { get; set; }
        public Nullable<System.DateTime> CASE_FIDETIME { get; set; }
        public string CASE_BRIEFINFO { get; set; }
        public Nullable<decimal> CASE_TYPE { get; set; }
        public string CASE_OVERREMARK { get; set; }
        public string CASE_LABEL { get; set; }
        public Nullable<decimal> CASE_STATUS { get; set; }
        public Nullable<System.DateTime> CASE_OVERTIME { get; set; }
        public Nullable<System.DateTime> CASE_CREATETIME { get; set; }
        public Nullable<System.DateTime> CASE_WARNINGTIME { get; set; }
        public string VICTIM { get; set; }
        public string VICTIM_CARDTYPE { get; set; }
        public string VICTIM_CARDNUM { get; set; }
        public string VICTIM_PHONENUM { get; set; }
        public string SUSPECT_NAME { get; set; }
        public string SUSPECT_CARDTYPE { get; set; }
        public string SUSPECT_CARDNUM { get; set; }
        public string SUSPECT_PHONENUM { get; set; }
        public string CASE_WARNINGPOLICE { get; set; }
        public string ALARMPEOPLE { get; set; }
        public string ALARMPEOPLE_CARDTYPE { get; set; }
        public string ALARMPEOPLE_CARDNUM { get; set; }
        public string ALARMPEOPLE_PHONENUM { get; set; }
        public string COLLECTIONMARK { get; set; }
        public string IS_DEL { get; set; }
        public string MAIN_CLUEID { get; set; }
    }
}
