//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIPF_CASE_RELATED_ASS
    {
        public string ID { get; set; }
        public string CASEID { get; set; }
        public string CASERELATEDID { get; set; }
        public string CREATER { get; set; }
        public Nullable<System.DateTime> CREATE_TM { get; set; }
        public string CREATER_ORG { get; set; }
        public string REMARK { get; set; }
        public string IS_DEL { get; set; }
    }
}
